import { useState } from "react";
const API_URL=import.meta.env.VITE_API_URL||"http://localhost:8000";
const samples={spam:"Congratulations! You have won a FREE cash prize. Click http://bit.ly/reward now to claim your reward!",safe:"Hi team, the meeting has been moved to 3 PM tomorrow. Please review the attached agenda before the call."};
export default function App(){
 const [token,setToken]=useState(localStorage.getItem("mailguard_token")||""),[authMode,setAuthMode]=useState("login"),[authEmail,setAuthEmail]=useState(""),[authPassword,setAuthPassword]=useState("");\n const [text,setText]=useState(""),[raw,setRaw]=useState(""),[result,setResult]=useState(null),[header,setHeader]=useState(null),[mode,setMode]=useState("message"),[loading,setLoading]=useState(false),[error,setError]=useState(""),[batch,setBatch]=useState([]),[url,setUrl]=useState(""),[urlResult,setUrlResult]=useState(null),[comparison,setComparison]=useState(null),[analytics,setAnalytics]=useState(null);
 async function request(path,body){const r=await fetch(API_URL+path,{method:"POST",headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Analysis failed");return d}
 async function loadAnalytics(){try{setAnalytics(await fetch(API_URL+"/analytics").then(r=>r.json()))}catch(e){setError(e.message)}}
 async function loadComparison(){try{setComparison(await fetch(API_URL+"/model-comparison").then(r=>r.json()))}catch(e){setError(e.message)}}
 async function authenticate(){setLoading(true);setError("");try{const d=await request("/auth/"+authMode,{email:authEmail,password:authPassword});localStorage.setItem("mailguard_token",d.access_token);setToken(d.access_token)}catch(e){setError(e.message)}finally{setLoading(false)}}\n async function analyzeUrl(){if(!url.trim())return;setLoading(true);setError("");try{setUrlResult(await request("/analyze/url",{url}))}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function analyze(){if(!text.trim())return;setLoading(true);setError("");try{setResult(await request("/predict",{text}));setHeader(null)}catch(e){setError(e.message+". Check that FastAPI is running.")}finally{setLoading(false)}}
 async function analyzeFile(e){const f=e.target.files?.[0];if(!f)return;setLoading(true);setError("");try{const v=await f.text();setRaw(v);setMode("raw");setHeader(await request("/analyze/raw-email",{raw_email:v}));setResult(null)}catch(e){setError(e.message)}finally{setLoading(false)}}\n async function analyzeBatch(e){const f=e.target.files?.[0];if(!f)return;setLoading(true);setError("");try{const rows=(await f.text()).split(/\\r?\\n/).map(v=>v.trim()).filter(Boolean);const emails=rows[0]?.toLowerCase().includes("email")?rows.slice(1):rows;setBatch((await request("/predict/batch",{emails})).results)}catch(e){setError(e.message)}finally{setLoading(false)}}\n async function analyzeRaw(){if(!raw.trim())return;setLoading(true);setError("");try{setHeader(await request("/analyze/raw-email",{raw_email:raw}));setResult(null)}catch(e){setError(e.message+". Check that FastAPI is running.")}finally{setLoading(false)}}
 const analysis=result||header?.body_analysis;
 return <main className="shell">
 <nav className="nav"><div className="brand"><span className="brand-mark">✉</span><span>MailGuard <b>AI</b></span></div><span className="status"><i/> {token?"Authenticated":"AI engine ready"}</span></nav>
 <section className="card auth-panel"><div className="card-head"><div><h2>🔐 {authMode==="login"?"Sign in":"Create account"}</h2><p>Secure your personal scan history.</p></div><span className="pill">ACCOUNT</span></div><div className="auth-form"><input type="email" value={authEmail} onChange={e=>setAuthEmail(e.target.value)} placeholder="Email address"/><input type="password" value={authPassword} onChange={e=>setAuthPassword(e.target.value)} placeholder="Password (8+ characters)"/><button className="analyze" onClick={authenticate} disabled={loading||!authEmail||!authPassword}>{loading?"Please wait…":authMode==="login"?"Sign in":"Create account"}</button></div><button className="auth-switch" onClick={()=>setAuthMode(authMode==="login"?"register":"login")}>{authMode==="login"?"Need an account? Create one":"Already have an account? Sign in"}</button></section>
 <section className="hero"><div className="eyebrow">INTELLIGENT EMAIL SECURITY</div><h1>Know what’s in your inbox<br/><span>before you click.</span></h1><p>Analyze message content or inspect raw email headers, authentication results, URLs, and model evidence.</p></section>
 <div className="tabs"><button className={mode==="message"?"active":""} onClick={()=>{setMode("message");setError("")}}>Message scanner</button><button className={mode==="raw"?"active":""} onClick={()=>{setMode("raw");setError("")}}>Raw email analyzer</button></div>
 <section className="url-panel card"><div className="card-head"><div><h2>🔗 URL Intelligence</h2><p>Inspect a link for common phishing characteristics before opening it.</p></div><span className="pill">URL</span></div><div className="url-form"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com/login"/><button className="analyze" onClick={analyzeUrl} disabled={loading||!url.trim()}>{loading?"Checking…":"Analyze URL →"}</button></div>{urlResult&&<div className="url-report"><div><strong>{urlResult.risk_score}/100</strong><small>{urlResult.risk_level.toUpperCase()} RISK</small></div><div><b>{urlResult.hostname||"Unknown host"}</b><p>{urlResult.reasons.length?urlResult.reasons.join(" · "):"No obvious structural red flags detected."}</p></div></div>}</section>
 <section className="workspace">
 <div className="card composer"><div className="card-head"><div><h2>{mode==="message"?"Analyze an email":"Inspect raw email"}</h2><p>{mode==="message"?"Paste message content below.":"Paste a complete .eml / raw email with headers."}</p></div><span className="pill">{mode==="message"?"NLP":"HEADERS"}</span></div>
 <textarea value={mode==="message"?text:raw} onChange={e=>mode==="message"?setText(e.target.value):setRaw(e.target.value)} placeholder={mode==="message"?"Paste an email, SMS, or message here...":"From: sender@example.com\nReply-To: ...\nAuthentication-Results: ...\nSubject: ...\n\nEmail body..."} />
 {mode==="message"&&<div className="samples"><span>Try a sample:</span><button onClick={()=>setText(samples.spam)}>Spam</button><button onClick={()=>setText(samples.safe)}>Safe</button></div>}
 <button className="analyze" onClick={mode==="message"?analyze:analyzeRaw} disabled={loading||!(mode==="message"?text:raw).trim()}>{loading?"Analyzing…":mode==="message"?"Analyze message →":"Inspect email →"}</button>{error&&<div className="error">{error}</div>}
 </div>
 <div className="card result">{!analysis?<div className="empty"><div className="shield">◈</div><h2>Your security report</h2><p>Results will include classification, risk, URLs, explanations, and email authentication.</p></div>:
 <><div className="card-head"><div><h2>Security analysis</h2><p>Prediction, risk score and security intelligence.</p></div><span className={`badge ${analysis.prediction}`}>{analysis.label}</span></div>
 <div className="score"><div><small>RISK SCORE</small><strong>{analysis.risk_score}<em>/100</em></strong></div><div className={`risk ${analysis.risk_level}`}>{analysis.risk_level.toUpperCase()} RISK</div></div>
 <div className="meter"><span style={{width:`${analysis.risk_score}%`}}/></div>
 <div className="stats"><div><small>SPAM PROBABILITY</small><b>{analysis.spam_probability}%</b></div><div><small>CONFIDENCE</small><b>{analysis.confidence}%</b></div><div><small>URLS FOUND</small><b>{analysis.url_analysis?.url_count??0}</b></div></div>
 {header&&<><div className="signals"><h3>Email identity</h3><div className="header-grid"><span>From</span><b>{header.headers.from||"—"}</b><span>Reply-To</span><b>{header.headers.reply_to||"—"}</b><span>Subject</span><b>{header.headers.subject||"—"}</b><span>Received hops</span><b>{header.headers.received_hops}</b></div></div><div className="signals"><h3>Authentication</h3><div className="auth-grid">{["spf","dkim","dmarc"].map(k=><div className={`auth ${header.headers.authentication[k]==="pass"?"pass":"unknown"}`} key={k}><small>{k.toUpperCase()}</small><b>{header.headers.authentication[k]}</b></div>)}</div></div></>}
 <div className="signals"><h3>Risk signals</h3>{analysis.risk_signals.length?analysis.risk_signals.map((s,i)=><div className="signal" key={i}><span>!</span>{s}</div>):<div className="signal safe-signal"><span>✓</span>No obvious risk signals detected.</div>}</div>
 {analysis.explanation?.length>0&&<div className="signals explanation"><h3>Why the model decided this</h3><div className="evidence">{analysis.explanation.map((x,i)=><div className="evidence-item" key={i}><span>{x.impact>=0?"+":"−"}</span><b>{x.term}</b><small>{x.impact>=0?"toward spam":"away from spam"}</small></div>)}</div></div>}
 {analysis.url_analysis?.suspicious_urls?.length>0&&<div className="signals urls"><h3>Suspicious URLs</h3>{analysis.url_analysis.suspicious_urls.map((u,i)=><div className="signal" key={i}><span>↗</span><div><b>{u.url}</b><small>{u.reasons.join(" · ")}</small></div></div>)}</div>}
 </>}</div></section><footer>MailGuard AI · Explainable NLP email security · v3.1</footer></main>
}